### ISSUE TITLE
Running this project

### ISSUE THREAD

**Issue by raghunandy** [readren/akkaHttp-angular2-typescript#1]
I am a beginner. I am trying to access the index page with various url combinations. Please update the document. 

http://localhost:9000/index.html

**Comment by readren** [comment]
To start the web server:
1) Go to the project root folder with the `cd` command, type `activator`, and wait the project builder initialization. This may take several minutes the first time.
2) Then type `compile` and wait the builder builds the project. This also may take several minutes the first time.
3) Then type `re-start` to start the web server. If everything is fine, the last line in the console should say "listening to http://localhost:9000".
4) Open any web browser and type "http://localhost:9000" in the url address edit box. If everything is ok, you should see the TODO MVC example application running.

If you want the address "http://localhost:9000/index.html" also work, you should add another route to support it. I already did it, anyway. This is the code excerpt:
`val indexRoute: Route =
  pathSingleSlash {
    getFromResource(index)
  } ~
    pathPrefix("index.html") {
      getFromResource(index)
    }`

Note that there are two branches of this project that replace the TODO MVC application with the "quick start" and the "tour of heroes" applications I copied from the official [angular 2](https://angular.io/) page.
Thanks you for trying this seed :)
